#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://202.200.126.139:3306/SchoolEpidemic?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: acloggo
#    password: ENC(GM3R2SVlWDzVTXjtbcuel2eovlLKUhWF)
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: false
#
#
#logging:
#  config: classpath:log4j2.xml










spring:
  datasource:
    #  Mysql连接信息
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://202.200.126.139:3306/SchoolEpidemic?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: acloggo
    password: ENC(GM3R2SVlWDzVTXjtbcuel2eovlLKUhWF)
    #  数据源类别
    type: com.alibaba.druid.pool.DruidDataSource
    #  初始化大小
    druid:
      min-idle: 5
      initial-size: 5
      max-active: 20
      #      配置获取连接等待超时的时间（毫秒）
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接（毫秒）
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小的生存时间（毫秒）
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: false
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache ，并指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters

      filters: stat,wall





#spring:
#  datasource:
#    #  Mysql连接信息
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/SchoolEpidemic?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: 369cc
#    #  数据源类别
#    type: com.alibaba.druid.pool.DruidDataSource
#    #  初始化大小
#    druid:
#      min-idle: 5
#      initial-size: 5
#      max-active: 20
#      #      配置获取连接等待超时的时间（毫秒）
#      max-wait: 60000
#      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接（毫秒）
#      time-between-eviction-runs-millis: 60000
#      # 配置一个连接在池中最小的生存时间（毫秒）
#      min-evictable-idle-time-millis: 30000
#      validation-query: SELECT 1 FROM DUAL
#      test-while-idle: false
#      test-on-borrow: false
#      test-on-return: false
#      # 打开PSCache ，并指定每个连接上PSCache的大小
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      # 配置监控统计拦截的filters
#
#      filters: stat,wall
#
#
